### ISSUE TITLE
Explain howto contribute

### ISSUE THREAD

**Issue by kappapiana** [maertsen/cra-foss-diagram#1]
# Problem

While I welcome the use of a git repo and draw.io (I actually have installed an extension to codium to edit directly from within the IDE) this information might be an impediment to those less used to.

# Solution

Add a Contribute file where you describe howto. The most elegant way should be forking and editing in the forked branch, the making a pull request.

Another way is to open a pull request with a mocked changed via PNG or so.

**Comment by maertsen** [comment]
Thanks for the suggestion and you are right, it is pretty unclear how to contribute.

I welcome a pull request for the first option. The second one sounds like a good fallback.

**Comment by kappapiana** [comment]
Done
